<?php

namespace AppBundle\Repository;

/**
 * taskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class taskRepository extends \Doctrine\ORM\EntityRepository
{
}
